### ISSUE TITLE
libavfilter causing Segmentation fault to tvheadend

### ISSUE THREAD

**Issue by th0ma7** [jellyfin/jellyfin-ffmpeg#132] opened 2022-04-22 17:55 UTC
**Describe The Bug**
ffmpeg patched using https://github.com/jellyfin/jellyfin-ffmpeg/tree/jellyfin/debian/patches causing Segmentation fault to tvheadend due to libavfiler.  Details here: https://github.com/SynoCommunity/spksrc/issues/5222

**Steps To Reproduce**
N/A

**Expected Behavior**
N/A

**System (please complete the following information):**

- **Platform:** Linux 
- **Operating System:** Synology DSM7
- **Virtualization**: N/A (bare-metal & VM issue found)
- **Jellyfin Version:** N/A
- **Jellyfin-FFmpeg Version:** 4.4.1 with jellyfin patches enabled
- **Hardware Acceleration:** libva using either iHD or i965
- **CPU & GPU Model**: intel various

**MediaInfo**
N/A

**FFmpeg Logs**
N/A

**Additional Context**
N/A

**Comment by th0ma7** [comment] 2022-04-22 18:19
Found the faulty patch: https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/debian/patches/0032-add-async-support-for-qsv-vpp.patch

If I get this right, it segfault at `avfilter_register_all();` found with gdb as `#2  0x00005555558212ba in libav_init () at src/libav.c:322` here:
```
4   void
315 libav_init(void)
316 {
317   libav_vaapi_init();
318   libav_set_loglevel();
319   av_log_set_callback(libav_log_callback);
320   av_register_all();
321   avformat_network_init();
322   avfilter_register_all();
323   transcode_init();
324 }
```

Disabling patch `0032-add-async-support-for-qsv-vpp.patch` solves the issue.

Note that it "may" be GCC specific:
1. until now, this only occurs on `x86_64` arch using GCC-7.5 (Synology Linux 7.0)
2. It does work ok using GCC-4.9 (e.g. Synology Linux 6.2)

**Comment by nyanmisaka** [comment] 2022-04-23 08:57
It seems to be a GCC specific issue. I can't reproduce it with recent GCC versions.

Note that `avfilter_register_all()` was [deprecated in FFmpeg 4.0](https://github.com/FFmpeg/FFmpeg/blob/499e245b856733c3bbcd3ba23b406729343ed5fe/doc/APIchanges#L594) and has been [removed in the latest FFmpeg 5.0](https://github.com/FFmpeg/FFmpeg/commit/ec82ff89b600fbe67723f5b22661f0a4e67924ab).

**Comment by th0ma7** [comment] 2022-04-23 13:51
Good to know, thnx for the info.  I'll pass it on to TVH developpers.
As for the GCC specific issue, is there anything I could do to provide you with more detailed traces?  I may need a few hints for that...

**Comment by Shadowghost** [comment] 2022-06-07 06:04
Since we upgraded to ffmpeg 5 and this does not seem to be something we can fix I'll close the issue.

**Closed as completed by Shadowghost** 2022-06-07 06:04 UTC
Labels: bug
