### ISSUE TITLE
jellyfin-ffmpeg for centos 7

### ISSUE THREAD

**Issue by Ho2x** [jellyfin/jellyfin-ffmpeg#51] opened 2020-08-19 14:35 UTC
No RPM jellyfin-ffmpeg for centos 7 ?
Thank's

**Comment by joshuaboniface** [comment] 2020-08-21 16:04
At this time we do no provide an RPM-based `jellyfin-ffmpeg`. Someone would need to contribute this as well as a standard build procedure similar to the Debian package.

**Comment by Shadowghost** [comment] 2022-06-07 06:12
Duplicate of #5

**Closed as completed by Shadowghost** 2022-06-07 06:12 UTC
