### ISSUE TITLE
Portable builds for musl-based Linux systems

### ISSUE THREAD

**Issue by FintasticMan** [jellyfin/jellyfin-ffmpeg#361] opened 2024-03-19 21:15 UTC
I would like to propose adding a build option to the CI for musl-based Linux distributions, such as Alpine Linux. From my rudimentary testing, jellyfin-ffmpeg should work just fine, with the exception of CUDA not being possible. I'm also not sure whether AMF is possible tbh, but I can look into that.

I've already made an Alpine Linux package, mostly using the configure options from the Arch package. That can be found [here](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/62512).

If this isn't something you'd be interested in, feel free to close.

**Comment by gnattu** [comment] 2024-03-19 21:28
Using musl can introduce compatibility issues with certain libraries we depends on, including those you mentioned. Additionally, OpenSSL is known to have issues when using musl on arm64 architectures(not sure if fixed now). Even the Jellyfin server itself doesn't work well with musl, as dotnet doesn't officially support it [and requires some hacks](https://github.com/dotnet/sdk/issues/24448). Since we don't officially support musl targets, I'm hesitant to provide official musl builds. We cannot guarantee the functionality for such builds either.

Feel free to fork this repo and modify the CI for musl if you want to build it for alpine, but you will be responsible for any unexpected behaviors for those builds.

**Closed as not planned by gnattu** 2024-03-19 21:28 UTC
Labels: enhancement

**Comment by FintasticMan** [comment] 2024-03-19 22:12
I see. Thanks for the explanation!

**Comment by Bond-009** [comment] 2024-03-20 11:09
We already provide musl (both x86_64 and aarch64) builds for unstable https://repo.jellyfin.org/?path=/server/linux/latest-unstable/amd64-musl
And I assume we will also have stable builds once 10.9 releases

**Comment by gnattu** [comment] 2024-03-20 11:12
> We already provide musl (both x86_64 and aarch64) builds for unstable https://repo.jellyfin.org/?path=/server/linux/latest-unstable/amd64-musl And I assume we will also have stable builds once 10.9 releases

But it is still hard to support for jellyfin-ffmpeg as we cannot ensure hardware acceleration would work properly.

**Comment by FintasticMan** [comment] 2024-03-20 12:07
Well, it should be obvious to anyone using musl that CUDA should never work, as there are no NVIDIA drivers for musl. AMF might work, haven't checked, and VAAPI and QSV should work fine. I would say that providing builds, even if untested, would be better than directing people to upstream FFmpeg.

**Comment by gnattu** [comment] 2024-03-20 13:58
> I would say that providing builds, even if untested, would be better than directing people to upstream FFmpeg.

However, it does not work that way. We have to deal with all the consequences of being untested, and if we mark it as an officially supported target, we will be responsible for fixing all the runtime and build time problems.

If you really, really want this happen, you can set up your own CI to create such builds, and we will document it on our website, marking it as community-supported, just like how we are doing with RPM builds in 10.9. We dropped all our official RPM repos in favor of RPMFusion's builds.
