### ISSUE TITLE
ASS Sub BUG

### ISSUE THREAD

**Issue by Snipy2k4** [jellyfin/jellyfin-ffmpeg#506] opened 2024-11-19 16:43 UTC
> As I wrote above, the problem is solved by manually extracting the ASS subtitles and adding them without changing them with the MKVTool and recreating the file.
> 
> For a large collection, this would mean, in my case, several 10,000 files that would have to be edited manually although it was once fixed and worked. With the update to version 10 this was broken again. 
> 
> To be honest, I have no desire to edit 10,000+ files manually as there is obviously another way. 
> 
> If this is the wrong section, I would ask you to move this so that the error can be addressed. Thank you
> 
>  

 _Originally posted by @Snipy2k4 in [#267](https://github.com/jellyfin/jellyfin-webos/issues/267#issuecomment-2481237254)_

**Comment by cchristchurch** [comment] 2024-11-24 22:52
Indeed I can confirm I see this issue too.

This seems to be a regression. The "random null character in the middle of the extracted subtitle file" problem was reported in multiple places more than a year ago ([jellyfin issue](https://github.com/jellyfin/jellyfin/issues/9344),  [upstream issue](https://fftrac-bg.ffmpeg.org/ticket/10203)), and then apparently fixed, but now re-ocurring.

I am currently running:
* jellyfin: 10.10.3+deb12
* jellyfin-ffmpeg7: 7.0.2-7-bookworm

I suspect this started happening again when upgrading to jellyfin 10.10x / jellyfin-ffmpeg7

**Comment by cchristchurch** [comment] 2024-11-24 23:03
@nyanmisaka sorry to bother you directly here -- I noticed you looked into the original issue [there](https://github.com/jellyfin/jellyfin/issues/9344) and followed up with upstream, do you have any clue why this is suddenly re-ocurring on recent versions of jellyfin?

**Comment by gnattu** [comment] 2024-11-24 23:42
I think the upstream “optimized out” the fix in https://github.com/FFmpeg/FFmpeg/commit/7bf1b9b35769b37684dd2f18a54f01d852a540c8

It is interesting that the author of the patch is also the maintainer of libass, the de-facto standard standard implementation of the ass spec.

Let me see if I can fix this, can you provide an mkv example that can reproduce this issue?

**Comment by cchristchurch** [comment] 2024-11-25 13:00
Ufortunately I'm not quite sure how to create a small file to reproduce this. Many files in my library have the issue but cannot be uploaded here as they're several GBs. 

I have tried to create smaller sample files using handbrake (my understanding from [this](https://fftrac-bg.ffmpeg.org/ticket/10203) is that the issue was first identified on files created with handbrake).

However it seems that my version of handbrake (1.6.1) no longer does that and once I re-encode something with it, ass subtitles can be extracted with ffmpeg without the null character in the middle.

**Comment by Snipy2k4** [comment] 2024-11-25 14:42
I don't know if this is specific to HandBrake versions or not, but I use version 1.8.2 (2024081000) for Windows. Unfortunately I don't see this NUL position in Notepad++ and I'm not so well versed in whether or how I can reproduce it correctly. 

What I do know is that if I have a video file with this problem, an “annoying” workaround for me is to extract the subtitles with gMKVExtractGUI and insert them again with MKVToolNix, replacing the “old subtitles” and virtually recreating the file. Then it works as it should in Jellyfin. - But that can't be the solution, because :

As I said, I could also help myself, but if you have a large collection of 10,000 files and more like me, it's a lot of work and actually, as I said, this has already been fixed, but with version 10 of Jellyfin it has been reinserted or the former fix has been undone.

For copyright reasons I would not like to upload one of my backup copies.

**Comment by gnattu** [comment] 2024-11-26 05:21
I literally tried handbrake from the very first version supports ASS subtitle (0.9.6) all the way to 1.3.0, and I cannot reproduce this. It would be extremely hard for me to fix this if I cannot verify my theory if nobody is willing to help me. I just modified one of my sample MKV with hex edit to manually insert a null char after the header and it seems to work with my draft patch where this null char will no longer be carried over. I will make a PR soon and I beg you to test with the action builds to see if it fixed your files as well.

**Comment by Snipy2k4** [comment] 2024-11-26 08:46
Hello,

Doesn't the original problem and its fix help you to identify, reproduce and fix the problem? I mean, it has been successfully fixed before.

You could start there and see what has changed with the version updates. 

Here is the original problem: 

https://github.com/jellyfin/jellyfin/issues/9344

The point here is not that nobody “WANTS” to help you, but that I don't want to illegally upload movies or series to the Internet. I hope you understand that. If I had a harmless file, I would make it available to you immediately.

**Comment by nyanmisaka** [comment] 2024-11-26 08:56
FF 6.0 (fixed with a custom patch)
FF 6.1 (fixed in upstream, confirmed by the original poster, we skipped this version)
FF 7.0 (upstream broke this again, and **the link to the sample has expired**)

https://fftrac-bg.ffmpeg.org/ticket/10203
> A small test file that exhibits the problem may be found here:
>[​https://0x0.st/oFTT.mkv](https://0x0.st/oFTT.mkv)

Install the potential fix from https://github.com/jellyfin/jellyfin-ffmpeg/pull/509/checks and see if it works for you.

**Comment by nyanmisaka** [comment] 2024-12-08 12:04
@Snipy2k4 @cchristchurch @Andreas-76 @seeseemelk
Can anyone install and try out ffmpeg with the fix included to see if it solves the problem?

https://github.com/jellyfin/jellyfin-ffmpeg/pull/509/checks

**Comment by cchristchurch** [comment] 2024-12-08 14:32
Sorry I got distracted away from all this and not at home for now, but I will be back and should be able to test this next weekend if no one had a chance yet.

**Comment by Andreas-76** [comment] 2024-12-08 14:35
@nyanmisaka 
I'm using docker image jellyfin/jellyfin so if you have put it in any of these
jellyfin/jellyfin:unstable
jellyfin/jellyfin:2024120205
then I can try 
or notify when you put it in docker.

**Closed as completed** 2024-12-14 07:55 UTC
Labels: bug

**Comment by rekom** [comment] 2024-12-15 17:13
Hello, i have the same problem but only with jellyfin-androidTV. If i play the file with the .ass subtile "included" in the webplayer it works, same with Swiftfin with my iOS devices. It does drive the app crazy. I can't launch any other files after that. : https://github.com/jellyfin/jellyfin-androidtv/issues/4304

**Comment by cchristchurch** [comment] 2024-12-18 17:46
A bit late to the party, but I can confirm the bug is now fixed when using `jellyfin-ffmpeg7` version `7.0.2-8-bookworm` on debian.

When extracting ASS subtitles from the same problematic MKVs that caused the issue before, I no longer see the infamous null character in the extracted file, and things work as expected 🎉 

Thanks a lot @gnattu @nyanmisaka for looking into this 🙏
